channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - freesasa
  - fastapi
  - uvicorn
  - python-multipart
  - httpx
  - jsonschema
  - jupyterlab
  - ipywidgets
  - jupyterlab_widgets
  - msgpack-python
  - nbformat
  - coverage
  - mypy<2
  - nox
  - pytest
  - pytest-cov
  - pyyaml
  - ruff
  - tox
  - openmm
  - pdbfixer
  - ambertools
  - gromacs
  - nodejs
  - python-build
  - pip
  - pip:
      - -e .[all]
