[tox]
env_list = py39, py310, py311, py312, lint, typecheck

[testenv]
extras = all
commands = python -m pytest {posargs}

[testenv:coverage]
extras = all
commands = python -m pytest --cov=pheat --cov-report=term-missing --cov-report=xml {posargs}

[testenv:coverage-html]
extras = all
commands = python -m pytest --cov=pheat --cov-report=term-missing --cov-report=xml --cov-report=html {posargs}

[testenv:lint]
extras = all
commands = python -m ruff check .

[testenv:typecheck]
extras = all
commands = python -m mypy src/pheat
